AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kaeru_go
  
  SAM Template for kaeru_go

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ArticleShowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: article-show/
      Handler: article-show
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /articles/{Id}
            Method: GET

Outputs:
  ArticleShowAPI:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/articles/id"

  ArticleShowFunction:
    Description: "article show function"
    Value: !GetAtt ArticleShowFunction.Arn

  ArticleShowFunctionIamRole:
    Description: "Implicit IAM Role created for Article Show function"
    Value: !GetAtt ArticleShowFunctionRole.Arn
